"use client"

import { useState } from "react"
import { Card } from "@/components/ui/card"
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"
import { ChevronDown, ChevronUp, Download } from "lucide-react"
import CodeBlock from "@/components/code-block"
import type { Finding } from "@/lib/types"

interface RoadmapTabProps {
  findings: Finding[]
}

export default function RoadmapTab({ findings }: RoadmapTabProps) {
  const [completed, setCompleted] = useState<Set<string>>(new Set())
  const [expanded, setExpanded] = useState<Set<string>>(new Set())

  const toggleComplete = (id: string) => {
    const newCompleted = new Set(completed)
    if (newCompleted.has(id)) {
      newCompleted.delete(id)
    } else {
      newCompleted.add(id)
    }
    setCompleted(newCompleted)
  }

  const toggleExpanded = (id: string) => {
    const newExpanded = new Set(expanded)
    if (newExpanded.has(id)) {
      newExpanded.delete(id)
    } else {
      newExpanded.add(id)
    }
    setExpanded(newExpanded)
  }

  const groupedFindings = {
    high: findings.filter((f) => f.severity === "critical" || f.severity === "high"),
    medium: findings.filter((f) => f.severity === "medium"),
    low: findings.filter((f) => f.severity === "low"),
  }

  const calculateStats = (items: Finding[]) => {
    const count = items.length
    const hours = (items.reduce((sum, f) => sum + f.minutesSaved, 0) / 60).toFixed(1)
    const cost = Math.round(Number.parseFloat(hours) * 85) // $85/hr rate
    return { count, hours, cost }
  }

  const highStats = calculateStats(groupedFindings.high)
  const mediumStats = calculateStats(groupedFindings.medium)
  const lowStats = calculateStats(groupedFindings.low)

  const totalCompleted = completed.size
  const totalIssues = findings.length
  const progressPercent = Math.round((totalCompleted / totalIssues) * 100)

  const handleDownload = () => {
    const markdown = generateMarkdown()
    const blob = new Blob([markdown], { type: "text/markdown" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = "roadmap.md"
    a.click()
    URL.revokeObjectURL(url)
  }

  const generateMarkdown = () => {
    let md = "# Refactor Roadmap\n\n"
    md += `Generated by LegacyLens\n\n`
    md += `## Progress: ${totalCompleted}/${totalIssues} completed (${progressPercent}%)\n\n`

    const sections = [
      { title: "🔴 High Priority", items: groupedFindings.high },
      { title: "🟡 Medium Priority", items: groupedFindings.medium },
      { title: "🔵 Low Priority", items: groupedFindings.low },
    ]

    sections.forEach((section) => {
      if (section.items.length > 0) {
        md += `## ${section.title}\n\n`
        section.items.forEach((finding, i) => {
          md += `### ${i + 1}. ${finding.title}\n\n`
          md += `- **Location:** ${finding.file}:${finding.line}\n`
          md += `- **Severity:** ${finding.severity}\n`
          md += `- **Time:** ${finding.minutesSaved} minutes\n`
          md += `- **Category:** ${finding.category}\n\n`
          md += `**Why it matters:**\n${finding.explanation}\n\n`
          md += `**Fix:**\n\`\`\`javascript\n${finding.fix}\n\`\`\`\n\n`
          md += `---\n\n`
        })
      }
    })

    return md
  }

  const renderGroup = (
    title: string,
    emoji: string,
    items: Finding[],
    stats: { count: number; hours: string; cost: number },
  ) => {
    if (items.length === 0) return null

    return (
      <div className="space-y-4">
        <div className="flex items-center gap-3">
          <h3 className="text-xl font-semibold text-foreground">
            {emoji} {title}
          </h3>
          <span className="text-sm text-muted-foreground">
            ({stats.count} issues · {stats.hours}hrs · ${stats.cost})
          </span>
        </div>

        <div className="space-y-3">
          {items.map((finding) => (
            <Card key={finding.id} className="bg-[#151b2e] border-[#1e2739] p-4">
              <div className="flex items-start gap-3">
                <Checkbox
                  checked={completed.has(finding.id)}
                  onCheckedChange={() => toggleComplete(finding.id)}
                  className="mt-1"
                />
                <div className="flex-1 space-y-2">
                  <div className={completed.has(finding.id) ? "line-through text-muted-foreground" : ""}>
                    <div className="font-medium text-foreground">{finding.title}</div>
                    <div className="text-sm text-muted-foreground">
                      {finding.file}:{finding.line} · {finding.minutesSaved}min · {finding.category}
                    </div>
                  </div>

                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => toggleExpanded(finding.id)}
                    className="text-primary hover:text-primary/80 p-0 h-auto"
                  >
                    {expanded.has(finding.id) ? (
                      <>
                        Hide Details <ChevronUp className="w-4 h-4 ml-1" />
                      </>
                    ) : (
                      <>
                        Show Details <ChevronDown className="w-4 h-4 ml-1" />
                      </>
                    )}
                  </Button>

                  {expanded.has(finding.id) && (
                    <div className="space-y-4 pt-4 animate-in slide-in-from-top-2 fade-in">
                      <div>
                        <div className="text-sm font-semibold text-foreground mb-2">Why it matters:</div>
                        <p className="text-sm text-muted-foreground">{finding.explanation}</p>
                      </div>
                      <div>
                        <div className="text-sm font-semibold text-foreground mb-2">Fix:</div>
                        <CodeBlock code={finding.fix} />
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </Card>
          ))}
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-8">
      {/* Progress Bar */}
      <Card className="bg-[#151b2e] border-[#1e2739] p-6">
        <div className="space-y-2">
          <div className="flex items-center justify-between text-sm">
            <span className="text-foreground font-medium">Progress</span>
            <span className="text-muted-foreground">
              {totalCompleted}/{totalIssues} completed ({progressPercent}%)
            </span>
          </div>
          <div className="h-2 bg-[#1e2739] rounded-full overflow-hidden">
            <div className="h-full bg-primary transition-all duration-500" style={{ width: `${progressPercent}%` }} />
          </div>
        </div>
      </Card>

      {/* Groups */}
      {renderGroup("HIGH PRIORITY", "🔴", groupedFindings.high, highStats)}
      {renderGroup("MEDIUM PRIORITY", "🟡", groupedFindings.medium, mediumStats)}
      {renderGroup("LOW PRIORITY", "🔵", groupedFindings.low, lowStats)}

      {/* Download Button */}
      <div className="flex justify-center pt-4">
        <Button
          onClick={handleDownload}
          size="lg"
          className="bg-primary hover:bg-primary/90 text-primary-foreground gap-2"
        >
          <Download className="w-5 h-5" />
          Download Roadmap.md
        </Button>
      </div>
    </div>
  )
}
